package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("привет")
    void generatedTest() {
        step("Открыть https://github.com/qa-guru/allure-notifications", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://github.com/qa-guru/allure-notifications'", () ->
            open("https://github.com/qa-guru/allure-notifications"));

        step("Page title should have text 'GitHub - qa-guru/allure-notifications: jar, that draws piechart from results and sends it with link to build to messenger'", () -> {
            String expectedTitle = "GitHub - qa-guru/allure-notifications: jar, that draws piechart from results and sends it with link to build to messenger";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://github.com/qa-guru/allure-notifications'", () ->
            open("https://github.com/qa-guru/allure-notifications"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}